-- AlterTable
ALTER TABLE "Deal" ADD COLUMN     "sellerCommission" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "supplierCommission" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "sellerCommission" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "supplierCommission" DOUBLE PRECISION NOT NULL DEFAULT 0;
